SimpleBlog/Controllers/DatatablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EF;

namespace SimpleBlog.Controllers
{
    public class DatatablesController : Controller
    {

        SimpleBlogDbContext db = new SimpleBlogDbContext();
        // GET: Datatables
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult getBlogs()
        {
            IQueryable<Blog> query = db.Blogs;

            var data = query.Select(p => new
            {
                ID = p.ID,
                CategoryId = p.CategoryId,
                Subject = p.Subject,
                Body = p.Body,
                DatePosted = p.DatePosted,
                Type = p.Type,
                OtherType = p.OtherType,
                CategoryName = p.Category.CategoryName
            }).ToList();

            var dataJson = new { data };
            return Json(dataJson, JsonRequestBehavior.AllowGet);

        }

        // Delete multi record
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult DeleteRecords(String[] UserIDs)
        {
            List<int> ids = UserIDs.Select(x => Int32.Parse(x)).ToList();

            if (ids != null & ids.Count() > 0)
            {
                List<Blog> selectedList = db.Blogs.Where(a => ids.Contains((int)a.ID)).ToList();
                foreach (var i in selectedList)
                {
                    db.Blogs.Remove(i);
                }
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

SimpleBlog/Views/Datatables/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript">

        // Select table
        function updateDataTableSelectAllCtrl(table) {
            var $table = table.table().node();
            var $chkbox_all = $('tbody input[type="checkbox"]', $table);
            var $chkbox_checked = $('tbody input[type="checkbox"]:checked', $table);
            var chkbox_select_all = $('thead input[name="select_all"]', $table).get(0);

            // If none of the checkboxes are checked
            if ($chkbox_checked.length === 0) {
                chkbox_select_all.checked = false;
                if ('indeterminate' in chkbox_select_all) {
                    chkbox_select_all.indeterminate = false;
                }

                // If all of the checkboxes are checked
            } else if ($chkbox_checked.length === $chkbox_all.length) {
                chkbox_select_all.checked = true;
                if ('indeterminate' in chkbox_select_all) {
                    chkbox_select_all.indeterminate = false;
                }

                // If some of the checkboxes are checked
            } else {
                chkbox_select_all.checked = true;
                if ('indeterminate' in chkbox_select_all) {
                    chkbox_select_all.indeterminate = true;
                }
            }
        }
        // Shorthand for $( document ).ready()
        $(function () {

            var rows_selected = [];
            var table = $('#tblBlog').DataTable({
                "searching": true,
                "ordering": true,
                "pagingType": "full_numbers",
                "ajax": "/Datatables/getBlogs",
                "autoWidth": true,
                "aLengthMenu": [[2, 4, 8, -1], [2, 4, 8, "All"]],
                "iDisplayLength": 4,        
                "columns": [
                    {
                        'render': function (data, type, full, meta) {
                            
                            return '<input type="checkbox">';
                        },
                        "targets": 'no-sort',
                    },
                    { "title": "ID", "data": "ID" },
                    { "data": "CategoryId" },
                    { "data": "Subject" },
                    { "data": "Body" },
                    { "data": "DatePosted" },
                    { "data": "Type" },
                    { "data": "OtherType" },
                    { "title": "Category Name", "data": "CategoryName" }
                ],
                "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    $(nRow).attr("id", aData.ID);
                    return nRow;
                },
                'rowCallback': function (row, data, dataIndex) {
                    // If row ID is in the list of selected row IDs
                    if ($.inArray(rowId, rows_selected) !== -1) {
                        $(row).find('input[type="checkbox"]').prop('checked', true);
                        $(row).addClass('selected');
                    }
                }
            });


            // Handle click on checkbox
            $('#tblBlog tbody').on('click', 'input[type="checkbox"]', function (e) {
                var $row = $(this).closest('tr');

                // Get row data
                var data = table.row($row).data();

                // Get row ID
                var rowId = data[0];

                // Determine whether row ID is in the list of selected row IDs
                var index = $.inArray(rowId, rows_selected);

                // If checkbox is checked and row ID is not in list of selected row IDs
                if (this.checked && index === -1) {
                    rows_selected.push(rowId);

                    // Otherwise, if checkbox is not checked and row ID is in list of selected row IDs
                } else if (!this.checked && index !== -1) {
                    rows_selected.splice(index, 1);
                }

                if (this.checked) {
                    $row.addClass('selected');
                } else {
                    $row.removeClass('selected');
                }

                // Update state of "Select all" control
                updateDataTableSelectAllCtrl(table);

                // Prevent click event from propagating to parent
                e.stopPropagation();
            });

            // Handle click on "Select all" control
            $('thead input[name="select_all"]', table.table().container()).on('click', function (e) {
                if (this.checked) {
                    $('#tblBlog tbody input[type="checkbox"]:not(:checked)').trigger('click');
                } else {
                    $('#tblBlog tbody input[type="checkbox"]:checked').trigger('click');
                }

                // Prevent click event from propagating to parent
                e.stopPropagation();
            });

            // Handle table draw event
            table.on('draw', function () {
                // Update state of "Select all" control
                updateDataTableSelectAllCtrl(table);
            });

            // Handle form submission event
            $('#frm-blog').on('submit', function (e) {
                //e.preventDefault();
                var form = this;

                var rowcollection = table.$("tr.selected", { "page": "all" });
                $.each(rowcollection, function (index, rowId) {
                    // Create a hidden element
                    var trId = $(this).attr("id");
                    console.log("Foreach all row !!! Row ID = " + trId);

                    $(form).append(
                        $('<input>')
                            .attr('type', 'hidden')
                            .attr('name', 'UserIDs[]')
                            .val(trId)
                    );
                });

                //// FOR DEMONSTRATION ONLY

                //// Output form data to a console
                //$('#example-console').text($(form).serialize());
                //console.log("Form submission", $(form).serialize());

                //// Remove added elements
                //$('input[name="id\[\]"]', form).remove();

                // Prevent actual form submission
                 
            });
        });
    </script>
}

@using (Html.BeginForm("DeleteRecords", "Datatables", FormMethod.Post, new { id = "frm-blog" }))
{
    @Html.AntiForgeryToken()
    <table id="tblBlog" class="display" cellspacing="0" data-page-length="5">
        <thead>
            <tr>
                <th><input name="select_all" value="1" type="checkbox"></th>
                <th>ID</th>
                <th>CategoryId</th>
                <th>Subject</th>
                <th>Body</th>
                <th>DatePosted</th>
                <th>Type</th>
                <th>OtherType</th>
                <th>Category Name</th>
            </tr>
        </thead>
    </table>
    <pre id="example-console"></pre>
    <p><button>Submit</button></p>
}